### ISSUE TITLE
module name issue and "colour" issues in beginners.py

### ISSUE THREAD

**Issue by borabosna** [CentricWebEstate/pieisreal#1]
Working under Python 3.5.1, I installed pieisreal-3.0-py3.5.egg by using
`setup.py build`,
and after
`setup.py install`
However,
`from livewires import beginners`
etc. do not work and give error "No module named 'livewires'"

Instead,
`from pieisreal import beginners`
etc. works. So I think you need to update the instructions under "Checking It Works" in README.md to reflect this.

Moreover,
`from pieisreal import beginners`
did not work at first either. It said "NameError: name 'Colour' is not defined".
`from pieisreal import colour`
gives the same error.

I had to go to line 170 in beginners.py and the lines below it to change every instance of 
`Colour(...`
to
`Color(...`

before I made the build. That made it work. This also meant that one must use 
`from pieisreal import color`
instead of 
`from pieisreal import colour` 
(which does not work out of the box.)

After these changes, all four of
`from pieisreal import *`
`from pieisreal import beginners`
`from pieisreal import color`
`from pieisreal import games`
work fine.

By the way, I really appreciate what you are doing for Python 3.5 compatibility. I am new to Python and programming in general and wanted to start with the latest version but the community is very divided and behind 3.5, which makes it very difficult for a beginner like myself. Thanks for all your hard work!

**Comment by jaitaiwan** [comment]
Hey borabosna thanks for picking out that readme issue!

As far as the color stuff is concerned Ive updated all the pdfs but and I believe that color is spelt the american way in this repo.

May I ask how you found this repo and why livewires?

**Comment by jaitaiwan** [comment]
FYI the game module wont work just yet as pygame is still yet to have a stable py3k version. I've been playing around with pyglet which is py3k compatible and I'm tempted to rewrite this module to use pyglet instead...

Heres a link to my idarb cloneish pyglet game work in progress if that helps... https://github.com/jaitaiwan/idabb

**Comment by borabosna** [comment]
I was using an old book "Python Programming for the Absolute Beginner" which uses livewires, but I do not have its CD, so I looked up livewires and then came here due to Python 3.5

**Comment by jaitaiwan** [comment]
I'm surprised you found it! How did you go from looking for livewires and finding PieIsReal? Also I've literally just uploaded new sheets for PieIsReal so check out the releases section here on github.

**Comment by borabosna** [comment]
As for game module, I found a Python 3.5 compatible, 64bit version of pygame here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame
Are you saying this is unstable?

**Comment by borabosna** [comment]
I kept searching the livewires Github and reading comments and I saw your comments there to the author under issues called "Update for python 3 compatibility"

**Comment by jaitaiwan** [comment]
Ah gotcha. Unfortunately yes, that's pygame 1.9.2 alpha 0. So unstable. I wouldn't mind providing an unstable version but unfortunately there's no single configuration I can add to the setup.py file so that running `python setup.py install` will pull down the correct version of pygame for ANY platform. It doesn't actually stop you from installing it manually yourself and using the game module anyway...

**Comment by borabosna** [comment]
Yeah I installed it manually and gonna try it out. I like being guinea pigs for alphas, it's fun in its own way. If it doesn't work I'll just skip that section in the book. I got the sheets by the way, thanks.

**Comment by jaitaiwan** [comment]
No worries. If it doesn't work hit me up, might be able to work together to make sure it does :)

**Comment by borabosna** [comment]
I found something interesting, this college course has livewires for Python 3:
http://www.bernstein-plus-sons.com/.dowling/CSC1023S12/
It only has color and games, not beginners.

**Comment by jaitaiwan** [comment]
That's frustrating. It looks like the py3k version you found at that uni doesn't have an auto install for pygame either. This library should work with pygame 1.9.2a0 if you can get it installed. Give it a go and let me know.
